name: FinalProjectM5
channels:
  - conda-forge
dependencies:
  - python=3.8.19
  - pandas=2.0.3
  - matplotlib=3.7.3
  - seaborn=0.12.2
  - statsmodels=0.14.0
  - plotly=5.19.0
  - statsforecast=1.7.5
  - scikit-learn=1.3.0
  - xgboost=2.0.3
  - joblib=1.4.2
  - typing_extensions=4.11.0
  - tqdm=4.66.4
  - scipy=1.10.1
  - shap=0.44.1
